# Generated by Django 2.0.9 on 2019-03-11 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('abbr', models.CharField(help_text='MXN, COL, HON, GUA', max_length=255, verbose_name='Abreviatura')),
                ('is_active', models.BooleanField(default=True, verbose_name='País Activo?')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Peso Colombiano, Peso Mexicano, Quetzal', max_length=255, verbose_name='Nombre')),
                ('abbr', models.CharField(help_text='COP, MXN, GTQ', max_length=10, verbose_name='Abreviatura')),
                ('is_active', models.BooleanField(default=True, verbose_name='Divisa Activa?')),
            ],
            options={
                'verbose_name': 'Divisa',
                'verbose_name_plural': 'Divisas',
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Ingresa el mes en el que tienen validez estas tasas de cambio', verbose_name='Mes')),
                ('exchange_dolar', models.IntegerField(help_text='Tasa de cambio para prestamos, abonos e intereses de la divisa a dolar', verbose_name='Cambio divisa a Dolar')),
                ('exchange_cop', models.IntegerField(help_text='Factor de cambio para prestamos, abonos e intereses de la divisa a peso colombiano', verbose_name='Factor divisa a Peso Colombiano')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_config.Currency', verbose_name='Divisa')),
            ],
            options={
                'verbose_name': 'Tasa de cambio',
                'verbose_name_plural': 'Tasas de cambio',
            },
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_config.Currency', verbose_name='Divisa'),
        ),
    ]
