# Generated by Django 2.0.9 on 2018-12-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='abbr',
            field=models.CharField(default='COL', help_text='MXN, COL, HON, GUA', max_length=255, verbose_name='Abreviatura'),
            preserve_default=False,
        ),
    ]
