# Generated by Django 2.0.9 on 2019-03-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'País', 'verbose_name_plural': 'Paises'},
        ),
    ]
