# Generated by Django 2.0.9 on 2019-01-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_config', '0002_country_abbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='País Activo?'),
        ),
        migrations.AddField(
            model_name='currency',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Divisa Activa?'),
        ),
    ]
