# Generated by Django 2.0.9 on 2019-05-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_config', '0002_auto_20190515_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='exchange_cop_abono',
            field=models.FloatField(default=0, help_text='Factor de cambio para prestamos, abonos e intereses de la divisa a peso colombiano', verbose_name='Factor divisa a Peso Colombiano (Abono)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchange',
            name='exchange_dolar_abono',
            field=models.FloatField(default=0, help_text='Tasa de cambio para prestamos, abonos e intereses de la divisa a dolar', verbose_name='Cambio divisa a Dolar (Abonos)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exchange',
            name='exchange_cop',
            field=models.FloatField(help_text='Factor de cambio para prestamos, abonos e intereses de la divisa a peso colombiano', verbose_name='Factor divisa a Peso Colombiano (Prestamo)'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='exchange_dolar',
            field=models.FloatField(help_text='Tasa de cambio para prestamos, abonos e intereses de la divisa a dolar', verbose_name='Cambio divisa a Dolar (Prestamo)'),
        ),
    ]
