# Generated by Django 2.0.9 on 2019-05-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_config', '0003_auto_20190520_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='exchange_cop',
            field=models.FloatField(help_text='Factor de cambio para prestamos de la divisa a peso colombiano', verbose_name='Factor divisa a Peso Colombiano (Prestamo)'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='exchange_cop_abono',
            field=models.FloatField(help_text='Factor de cambio para abonos e intereses de la divisa a peso colombiano', verbose_name='Factor divisa a Peso Colombiano (Abono)'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='exchange_dolar',
            field=models.FloatField(help_text='Tasa de cambio para prestamos de la divisa a dolar', verbose_name='Cambio divisa a Dolar (Prestamo)'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='exchange_dolar_abono',
            field=models.FloatField(help_text='Tasa de cambio para abonos e intereses de la divisa a dolar', verbose_name='Cambio divisa a Dolar (Abonos)'),
        ),
    ]
