# Generated by Django 2.0.9 on 2018-12-21 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general_config', '0002_country_abbr'),
        ('users', '0012_auto_20181221_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('concept_type', models.CharField(choices=[('SM', 'Simple'), ('DB', 'Doble partida')], max_length=5, verbose_name='Tipo de concepto')),
                ('crossover_type', models.CharField(blank=True, choices=[('PA', 'Socio Directo'), ('OF', 'Oficina')], max_length=5, null=True, verbose_name='Tipo de Cruce')),
                ('counterpart_name', models.CharField(help_text='Nombre de la contrapartida cuando el concepto es de cruce. Ejm. Venta--> Compra. ', max_length=255, verbose_name='Nombre Contrapartida')),
                ('relationship', models.CharField(blank=True, choices=[('UNIT', 'Unidad'), ('PERS', 'Socio, empleado'), ('COUNTRY', 'Pais'), ('PREST', 'Prestamo'), ('CHAIN', 'Cadena')], max_length=10, null=True, verbose_name='Relacion del movimiento')),
            ],
            options={
                'verbose_name': 'Concepto',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Valor del tope')),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Charge', verbose_name='Cargo')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concepts.Concept', verbose_name='Concepto')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_config.Country', verbose_name='Pais')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Socio, empleado')),
            ],
            options={
                'verbose_name': 'Tope',
            },
        ),
    ]
