# Generated by Django 2.0.9 on 2018-12-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='relationship',
            field=models.CharField(blank=True, choices=[('UNIT', 'Unidad'), ('PERS', 'Socio, empleado'), ('COUNTRY', 'Pais'), ('PREST', 'Prestamo'), ('CHAIN', 'Cadena'), ('OF', 'Oficina')], max_length=10, null=True, verbose_name='Relacion del movimiento'),
        ),
    ]
