# Generated by Django 2.0.9 on 2019-04-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0002_auto_20190408_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='is_informative',
            field=models.BooleanField(default=False, verbose_name='Tope informativo?'),
        ),
    ]
