# Generated by Django 2.0.9 on 2019-01-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0003_auto_20190116_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='counterpart_name',
            field=models.CharField(blank=True, help_text='Nombre de la contrapartida cuando el concepto es de cruce. Ejm. Venta--> Compra. ', max_length=255, null=True, verbose_name='Nombre Contrapartida'),
        ),
    ]
