# Generated by Django 2.0.9 on 2019-05-02 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190422_2016'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('concepts', '0003_stop_is_informative'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='report_by_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_charge_report', to='users.Charge', verbose_name='Informar por cargo'),
        ),
        migrations.AddField(
            model_name='stop',
            name='report_users',
            field=models.ManyToManyField(related_name='related_users_report', to=settings.AUTH_USER_MODEL, verbose_name='Informar usuarios'),
        ),
    ]
