# Generated by Django 2.0.9 on 2019-05-13 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0004_auto_20190502_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concept',
            options={'ordering': ['name'], 'verbose_name': 'Concepto'},
        ),
    ]
