# Generated by Django 2.0.9 on 2019-01-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0005_concept_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Concepto activo?'),
        ),
    ]
