# Generated by Django 2.0.9 on 2019-02-04 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0006_concept_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='counterpart_name',
        ),
        migrations.AddField(
            model_name='concept',
            name='counterpart',
            field=models.ForeignKey(blank=True, help_text='Concepto de contrapartida cuando el concepto es de cruce.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='concepts.Concept', verbose_name='Concepto Contrapartida'),
        ),
    ]
