# Generated by Django 2.0.9 on 2019-02-12 20:37

import concepts.models.concepts
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0008_auto_20190212_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='concept_type',
            field=enumfields.fields.EnumField(enum=concepts.models.concepts.ConceptType, max_length=2, verbose_name='Tipo de concepto'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='crossover_type',
            field=enumfields.fields.EnumField(blank=True, enum=concepts.models.concepts.CrossoverType, max_length=2, null=True, verbose_name='Tipo de cruce'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='relationship',
            field=enumfields.fields.EnumField(blank=True, enum=concepts.models.concepts.Relationship, max_length=7, null=True, verbose_name='Relación del movimiento'),
        ),
    ]
