version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: cajas_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: cajas_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    ports:
      - "5433:5432"
    env_file:
      - ./.envs/.local/.postgres

  celery_worker:
    <<: *django
    depends_on:
      - django
      - postgres
    ports: []
    command: /start-celeryworker.sh

  celery_beat:
    <<: *django
    depends_on:
      - django
      - postgres
    ports: []
    command: /start-celerybeat.sh

  redis:
    image: redis:3.2
