version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_nginx: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: cajas_production_django
    depends_on:
      - redis
    command: /start

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: cajas_production_nginx
    depends_on:
      - django
    volumes:
      - production_nginx:/root/.nginx
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  celery_worker:
    <<: *django
    depends_on:
      - django
      - nginx
    ports: []
    command: /start-celeryworker.sh

  celery_beat:
    <<: *django
    depends_on:
      - django
      - nginx
    ports: []
    command: /start-celerybeat.sh

  redis:
    image: redis:3.2
