# Generated by Django 2.0.9 on 2019-03-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='observations',
            field=models.TextField(blank=True, help_text='Motivo para deshabilitar el empleado', null=True, verbose_name='Motivo de despido'),
        ),
    ]
