# Generated by Django 2.0.9 on 2019-03-11 14:40

import cajas.users.models.employee
import cajas.users.models.partner
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('ip', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('action', models.CharField(choices=[('LI', 'Inicio de sesión'), ('LO', 'Cierre de sesión')], max_length=5, verbose_name='Acción')),
            ],
            options={
                'verbose_name': 'Log de autenticación',
                'verbose_name_plural': 'Logs de autenticación',
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Cargo',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_type', models.CharField(choices=[('FX', 'Salario Fijo'), ('PE', 'Porcentaje de comisión')], default='FX', max_length=2, verbose_name='Tipo de salario')),
                ('salary', models.IntegerField(default=0, verbose_name='Salario Empleado')),
                ('passport', models.FileField(upload_to=cajas.users.models.employee.user_passport_path, verbose_name='Pasaporte')),
                ('cv', models.FileField(upload_to=cajas.users.models.employee.user_cv_path, verbose_name='Hoja de vida')),
                ('is_daily_square', models.BooleanField(default=False, verbose_name='Es cuadre diario?')),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Charge', verbose_name='Cargo de empleado')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_employees', to='office.Office', verbose_name='Oficina')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código')),
                ('partner_type', enumfields.fields.EnumField(enum=cajas.users.models.partner.PartnerType, max_length=5, verbose_name='Tipo de socio')),
                ('is_daily_square', models.BooleanField(default=False, verbose_name='Es cuadre diario?')),
                ('consecutive', models.IntegerField(default=1, verbose_name='Consecutivo Mini-Socios')),
                ('direct_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Partner', verbose_name='Socio Directo')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.Office', verbose_name='Oficina')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='document_id',
            field=models.CharField(default='', max_length=15, verbose_name='Número Documento'),
        ),
        migrations.AddField(
            model_name='user',
            name='document_type',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadania'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte')], default='CC', max_length=3, verbose_name='Tipo Documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_abstract',
            field=models.BooleanField(default=True, verbose_name='Tiene acceso a la plataforma?'),
        ),
        migrations.AddField(
            model_name='partner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='authlogs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='partner',
            unique_together={('office', 'user')},
        ),
    ]
