# Generated by Django 2.0.9 on 2019-03-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_daily_square',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='is_daily_square',
        ),
        migrations.AddField(
            model_name='user',
            name='is_daily_square',
            field=models.BooleanField(default=False, verbose_name='Es cuadre diario?'),
        ),
    ]
