# Generated by Django 2.0.9 on 2019-04-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190408_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='office',
            field=models.ManyToManyField(blank=True, related_name='partners', to='office.OfficeCountry', verbose_name='Oficina por País'),
        ),
    ]
