# Generated by Django 2.0.9 on 2018-12-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181218_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_abstract',
            field=models.BooleanField(default=False, verbose_name='Es abstracto?'),
        ),
    ]
