# Generated by Django 2.0.9 on 2019-04-02 22:08

import cajas.users.models.employee
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190328_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=cajas.users.models.employee.user_cv_path, verbose_name='Hoja de vida'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to=cajas.users.models.employee.user_passport_path, verbose_name='Pasaporte'),
        ),
    ]
