# Generated by Django 2.0.9 on 2018-12-18 20:59

import cajas.users.models.employee
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181218_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.FileField(upload_to=cajas.users.models.employee.user_passport_path, verbose_name='Pasaporte')),
                ('cv', models.FileField(upload_to=cajas.users.models.employee.user_cv_path, verbose_name='Hoja de vida')),
                ('employee_type', models.CharField(choices=[('PRESI', 'Presidente'), ('SUBGER', 'Subgerente'), ('ASADMI', 'Asistente Administrativa'), ('ASENI', 'Administrador Senior'), ('AJUNI', 'Administrador Junior'), ('SECRE', 'Secretaria'), ('SUPERV', 'Supervisor'), ('COBRA', 'Cobrador'), ('TARJET', 'Tarjetero')], max_length=10, verbose_name='Tipo de empleado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
