# Generated by Django 2.0.9 on 2019-04-08 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_auto_20190408_1614'),
        ('users', '0003_auto_20190408_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='office',
        ),
        migrations.AddField(
            model_name='partner',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='office.OfficeCountry', verbose_name='Oficina por País'),
        ),
    ]
