# Generated by Django 2.0.9 on 2018-12-18 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
