# Generated by Django 2.0.9 on 2018-12-18 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181218_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_type', models.CharField(choices=[('DIR', 'Directo'), ('INDIR', 'Indirecto')], max_length=10, verbose_name='Tipo de empleado')),
                ('direct_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Partner', verbose_name='Socio Directo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
            },
        ),
    ]
