# Generated by Django 2.0.9 on 2019-04-21 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_group_groupemployee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Administrador de grupo'},
        ),
    ]
