# Generated by Django 2.0.9 on 2019-04-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190421_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(default=0, verbose_name='Salario Empleado'),
        ),
    ]
