# Generated by Django 2.0.9 on 2018-12-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_partner_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_abstract',
            field=models.BooleanField(default=False, verbose_name='Tiene acceso a la plataforma?'),
        ),
    ]
