# Generated by Django 2.0.9 on 2018-12-19 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181218_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='direct_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Partner', verbose_name='Socio Directo'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('DIR', 'Directo'), ('INDIR', 'Indirecto'), ('DJ', 'Don Juan')], max_length=10, verbose_name='Tipo de empleado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_abstract',
            field=models.BooleanField(default=True, verbose_name='Tiene acceso a la plataforma?'),
        ),
    ]
