# Generated by Django 2.0.9 on 2019-06-05 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_auto_20190427_1452'),
        ('users', '0009_auto_20190513_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySquareUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Employee', verbose_name='Empleado')),
                ('units', models.ManyToManyField(to='units.Unit', verbose_name='Unidades a cargo')),
            ],
            options={
                'verbose_name': 'Rutas de Cuadre Diario',
                'verbose_name_plural': 'Rutas de Cuadres Diarios',
            },
        ),
    ]
