# Generated by Django 2.0.9 on 2019-06-11 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_auto_20190502_1343'),
        ('users', '0010_dailysquareunits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailysquareunits',
            options={'verbose_name': 'Ruta a cargo', 'verbose_name_plural': 'Rutas a cargo'},
        ),
        migrations.AddField(
            model_name='group',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='office.OfficeCountry', verbose_name='Oficina'),
        ),
    ]
