# Generated by Django 2.0.9 on 2019-01-18 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190116_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('ip', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('action', models.CharField(choices=[('LI', 'Inicio de sesión'), ('LO', 'Cierre de sesión')], max_length=5, verbose_name='Acción')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de autenticación',
                'verbose_name_plural': 'Logs de autenticación',
            },
        ),
    ]
