# Generated by Django 2.0.9 on 2019-01-25 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_auto_20190125_2147'),
        ('users', '0014_authlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.Office', verbose_name='Oficina'),
        ),
    ]
