# Generated by Django 2.0.9 on 2019-01-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_partner_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código'),
        ),
    ]
