# Generated by Django 2.0.9 on 2019-01-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190125_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='Salario Empleado'),
        ),
    ]
