# Generated by Django 2.0.9 on 2019-01-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary_type',
            field=models.CharField(choices=[('FX', 'Salario Fijo'), ('PE', 'Porcentaje de comisión')], default='FX', max_length=2, verbose_name='Tipo de salario'),
        ),
    ]
