# Generated by Django 2.0.9 on 2019-02-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_employee_salary_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_daily_square',
            field=models.BooleanField(default=False, verbose_name='Es cuadre diarioo?'),
        ),
    ]
