# Generated by Django 2.0.9 on 2019-02-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190204_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_daily_square',
            field=models.BooleanField(default=False, verbose_name='Es cuadre diario?'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='is_daily_square',
            field=models.BooleanField(default=False, verbose_name='Es cuadre diario?'),
        ),
    ]
