# Generated by Django 2.0.9 on 2019-02-04 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0012_auto_20190204_2210'),
        ('users', '0021_auto_20190204_1939'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partner',
            unique_together={('user', 'office')},
        ),
    ]
