# Generated by Django 2.0.9 on 2019-02-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20190211_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='consecutive',
            field=models.IntegerField(default=1, verbose_name='Consecutivo Mini-Socios'),
        ),
    ]
