# Generated by Django 2.0.9 on 2019-03-06 19:26

import cajas.users.models.partner
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0014_auto_20190306_1658'),
        ('users', '0026_partner_consecutive'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_employees', to='office.Office', verbose_name='Oficina'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=enumfields.fields.EnumField(enum=cajas.users.models.partner.PartnerType, max_length=5, verbose_name='Tipo de socio'),
        ),
    ]
