# Generated by Django 2.0.9 on 2019-02-12 21:18

import cajas.users.models.partner
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_partner_consecutive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=enumfields.fields.EnumField(enum=cajas.users.models.partner.PartnerType, max_length=5, verbose_name='Tipo de socio'),
        ),
    ]
