# Generated by Django 2.0.9 on 2019-04-08 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concepts', '0001_initial'),
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementDailySquare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entra'), ('OUT', 'Sale')], max_length=10, verbose_name='Tipo de movimiento')),
                ('value', models.IntegerField(default=0, verbose_name='Valor')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP responsable')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo')),
                ('review', models.BooleanField(default=False, verbose_name='Movimiento Revisado?')),
                ('status', models.CharField(blank=True, choices=[('AP', 'Aprobado'), ('DE', 'Rechazado'), ('DI', 'Dispersado')], max_length=2, null=True, verbose_name='Estado de la revisión')),
                ('denied_detail', models.TextField(blank=True, null=True, verbose_name='Detalle del rechazo del movimiento')),
            ],
            options={
                'verbose_name': 'Movimiento del Cuadre Diario',
                'verbose_name_plural': 'Movimientos del Cuadre Diario',
            },
        ),
        migrations.CreateModel(
            name='MovementDonJuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entra'), ('OUT', 'Sale')], max_length=10, verbose_name='Tipo de movimiento')),
                ('value', models.IntegerField(default=0, verbose_name='Valor')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP responsable')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo')),
            ],
            options={
                'verbose_name': 'Movimiento de Don Juan',
                'verbose_name_plural': 'Movimientos de Don Juan',
            },
        ),
        migrations.CreateModel(
            name='MovementDonJuanUsd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entra'), ('OUT', 'Sale')], max_length=10, verbose_name='Tipo de movimiento')),
                ('value', models.IntegerField(default=0, verbose_name='Valor')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP responsable')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo')),
            ],
            options={
                'verbose_name': 'Movimiento de Don Juan',
                'verbose_name_plural': 'Movimientos de Don Juan',
            },
        ),
        migrations.CreateModel(
            name='MovementOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entra'), ('OUT', 'Sale')], max_length=10, verbose_name='Tipo de movimiento')),
                ('value', models.IntegerField(default=0, verbose_name='Valor')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP responsable')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo')),
            ],
            options={
                'verbose_name': 'Movimiento de la oficina',
                'verbose_name_plural': 'Movimientos de la oficina',
            },
        ),
        migrations.CreateModel(
            name='MovementPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entra'), ('OUT', 'Sale')], max_length=10, verbose_name='Tipo de movimiento')),
                ('value', models.IntegerField(default=0, verbose_name='Valor')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP responsable')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo')),
            ],
            options={
                'verbose_name': 'Movimiento del socio',
                'verbose_name_plural': 'Movimientos del socio',
            },
        ),
        migrations.CreateModel(
            name='MovementProvisioning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entra'), ('OUT', 'Sale')], max_length=10, verbose_name='Tipo de movimiento')),
                ('value', models.IntegerField(default=0, verbose_name='Valor')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP responsable')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo')),
            ],
            options={
                'verbose_name': 'Movimiento de aprovisionamiento',
                'verbose_name_plural': 'Movimientos de aprovisionamiento',
            },
        ),
        migrations.CreateModel(
            name='MovementRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entra'), ('OUT', 'Sale')], max_length=10, verbose_name='Tipo de movimiento')),
                ('value', models.IntegerField(default=0, verbose_name='Valor')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP responsable')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo')),
                ('observation', models.TextField(help_text='Observación por la cual se debería de aceptar el movimiento que sobrepasó el tope', verbose_name='Observación')),
                ('withdraw_reason', models.TextField(blank=True, null=True, verbose_name='Razón de solicitud de permiso retiro de socio')),
            ],
            options={
                'verbose_name': 'Requerimiento de Movimiento',
                'verbose_name_plural': 'Requerimientos de movimientos',
            },
        ),
        migrations.CreateModel(
            name='MovementWithdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entra'), ('OUT', 'Sale')], max_length=10, verbose_name='Tipo de movimiento')),
                ('value', models.IntegerField(default=0, verbose_name='Valor')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP responsable')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo')),
                ('observation', models.TextField(help_text='Observación por la cual se debería de aceptar el movimiento', verbose_name='Observación')),
                ('withdraw_reason', models.TextField(blank=True, null=True, verbose_name='Razón de solicitud de permiso retiro de socio')),
                ('box_daily_square', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_withdraw', to='boxes.BoxDailySquare', verbose_name='Caja Cuadre Diario')),
                ('box_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_withdraw', to='boxes.BoxPartner', verbose_name='Caja Socio')),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concepts.Concept', verbose_name='Concepto')),
            ],
            options={
                'verbose_name': 'Requerimiento de retiro',
                'verbose_name_plural': 'Requerimientos de retiro',
            },
        ),
    ]
