# Generated by Django 2.0.9 on 2019-03-11 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boxes', '0001_initial'),
        ('concepts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entra'), ('OUT', 'Sale')], max_length=10, verbose_name='Tipo de movimiento')),
                ('value', models.IntegerField(default=0, verbose_name='Valor')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP responsable')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo')),
            ],
            options={
                'verbose_name': 'Movimiento del país',
                'verbose_name_plural': 'Movimientos del país',
            },
        ),
        migrations.CreateModel(
            name='MovementDailySquare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entra'), ('OUT', 'Sale')], max_length=10, verbose_name='Tipo de movimiento')),
                ('value', models.IntegerField(default=0, verbose_name='Valor')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP responsable')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo')),
                ('review', models.BooleanField(default=False, verbose_name='Movimiento Revisado?')),
                ('status', models.CharField(blank=True, choices=[('AP', 'Aprobado'), ('DE', 'Rechazado'), ('DI', 'Dispersado')], max_length=2, null=True, verbose_name='Estado de la revisión')),
                ('denied_detail', models.TextField(blank=True, null=True, verbose_name='Detalle del rechazo del movimiento')),
            ],
            options={
                'verbose_name': 'Movimiento del Cuadre Diario',
                'verbose_name_plural': 'Movimientos del Cuadre Diario',
            },
        ),
        migrations.CreateModel(
            name='MovementDonJuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entra'), ('OUT', 'Sale')], max_length=10, verbose_name='Tipo de movimiento')),
                ('value', models.IntegerField(default=0, verbose_name='Valor')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP responsable')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo')),
            ],
            options={
                'verbose_name': 'Movimiento de Don Juan',
                'verbose_name_plural': 'Movimientos de Don Juan',
            },
        ),
        migrations.CreateModel(
            name='MovementOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entra'), ('OUT', 'Sale')], max_length=10, verbose_name='Tipo de movimiento')),
                ('value', models.IntegerField(default=0, verbose_name='Valor')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP responsable')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo')),
            ],
            options={
                'verbose_name': 'Movimiento de la oficina',
                'verbose_name_plural': 'Movimientos de la oficina',
            },
        ),
        migrations.CreateModel(
            name='MovementPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entra'), ('OUT', 'Sale')], max_length=10, verbose_name='Tipo de movimiento')),
                ('value', models.IntegerField(default=0, verbose_name='Valor')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP responsable')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo')),
                ('box_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='boxes.BoxPartner', verbose_name='Caja Socio')),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concepts.Concept', verbose_name='Concepto')),
            ],
            options={
                'verbose_name': 'Movimiento del socio',
                'verbose_name_plural': 'Movimientos del socio',
            },
        ),
    ]
