# Generated by Django 2.0.9 on 2019-04-08 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0001_initial'),
        ('concepts', '0002_auto_20190408_1614'),
        ('movement', '0001_initial'),
        ('units', '0001_initial'),
        ('boxes', '0003_auto_20190408_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementwithdraw',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='movementrequest',
            name='box_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_request', to='boxes.BoxPartner', verbose_name='Caja Socio'),
        ),
        migrations.AddField(
            model_name='movementrequest',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concepts.Concept', verbose_name='Concepto'),
        ),
        migrations.AddField(
            model_name='movementrequest',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='movementprovisioning',
            name='box_provisioning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='boxes.BoxProvisioning', verbose_name='Caja aprovisionamiento'),
        ),
        migrations.AddField(
            model_name='movementprovisioning',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concepts.Concept', verbose_name='Concepto'),
        ),
        migrations.AddField(
            model_name='movementprovisioning',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='movementpartner',
            name='box_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='boxes.BoxPartner', verbose_name='Caja Socio'),
        ),
        migrations.AddField(
            model_name='movementpartner',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concepts.Concept', verbose_name='Concepto'),
        ),
        migrations.AddField(
            model_name='movementpartner',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='movementoffice',
            name='box_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='boxes.BoxOffice', verbose_name='Caja oficina'),
        ),
        migrations.AddField(
            model_name='movementoffice',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concepts.Concept', verbose_name='Concepto'),
        ),
        migrations.AddField(
            model_name='movementoffice',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='movementdonjuanusd',
            name='box_don_juan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='boxes.BoxDonJuanUSD', verbose_name='Caja Don Juan USD'),
        ),
        migrations.AddField(
            model_name='movementdonjuanusd',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concepts.Concept', verbose_name='Concepto'),
        ),
        migrations.AddField(
            model_name='movementdonjuanusd',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='movementdonjuan',
            name='box_don_juan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='boxes.BoxDonJuan', verbose_name='Caja Don Juan Oficina'),
        ),
        migrations.AddField(
            model_name='movementdonjuan',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concepts.Concept', verbose_name='Concepto'),
        ),
        migrations.AddField(
            model_name='movementdonjuan',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='movementdailysquare',
            name='box_daily_square',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='boxes.BoxDailySquare', verbose_name='Caja Cuadre Diario'),
        ),
        migrations.AddField(
            model_name='movementdailysquare',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concepts.Concept', verbose_name='Concepto'),
        ),
        migrations.AddField(
            model_name='movementdailysquare',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general_config.Country', verbose_name='País'),
        ),
        migrations.AddField(
            model_name='movementdailysquare',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.OfficeCountry', verbose_name='Oficina'),
        ),
        migrations.AddField(
            model_name='movementdailysquare',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='movementdailysquare',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.Unit', verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='movementdailysquare',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_movements', to=settings.AUTH_USER_MODEL, verbose_name='Socio, empleado'),
        ),
    ]
