# Generated by Django 2.0.9 on 2019-01-18 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('units', '0002_auto_20190116_1523'),
        ('general_config', '0002_country_abbr'),
        ('office', '0007_officeitems_brand'),
        ('movement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementdailysquare',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general_config.Country', verbose_name='País'),
        ),
        migrations.AddField(
            model_name='movementdailysquare',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.Office', verbose_name='Oficina'),
        ),
        migrations.AddField(
            model_name='movementdailysquare',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.Unit', verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='movementdailysquare',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_movements', to=settings.AUTH_USER_MODEL, verbose_name='Socio, empleado'),
        ),
    ]
