# Generated by Django 2.0.9 on 2019-03-20 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_config', '0001_initial'),
        ('office', '0001_initial'),
        ('concepts', '0002_auto_20190320_2119'),
        ('units', '0001_initial'),
        ('boxes', '0002_auto_20190320_2119'),
        ('movement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movementpartner',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='movementoffice',
            name='box_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='boxes.BoxOffice', verbose_name='Caja oficina'),
        ),
        migrations.AddField(
            model_name='movementoffice',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concepts.Concept', verbose_name='Concepto'),
        ),
        migrations.AddField(
            model_name='movementoffice',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='movementdonjuan',
            name='box_don_juan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='boxes.BoxDonJuan', verbose_name='Caja Don Juan Oficina'),
        ),
        migrations.AddField(
            model_name='movementdonjuan',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concepts.Concept', verbose_name='Concepto'),
        ),
        migrations.AddField(
            model_name='movementdonjuan',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='movementdailysquare',
            name='box_daily_square',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='boxes.BoxDailySquare', verbose_name='Caja Cuadre Diario'),
        ),
        migrations.AddField(
            model_name='movementdailysquare',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concepts.Concept', verbose_name='Concepto'),
        ),
        migrations.AddField(
            model_name='movementdailysquare',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general_config.Country', verbose_name='País'),
        ),
        migrations.AddField(
            model_name='movementdailysquare',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.Office', verbose_name='Oficina'),
        ),
        migrations.AddField(
            model_name='movementdailysquare',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='movementdailysquare',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.Unit', verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='movementdailysquare',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_movements', to=settings.AUTH_USER_MODEL, verbose_name='Socio, empleado'),
        ),
        migrations.AddField(
            model_name='movementcountry',
            name='box_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='boxes.BoxCountry', verbose_name='Caja País'),
        ),
        migrations.AddField(
            model_name='movementcountry',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concepts.Concept', verbose_name='Concepto'),
        ),
        migrations.AddField(
            model_name='movementcountry',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
    ]
