# Generated by Django 2.0.9 on 2019-01-28 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0002_auto_20190118_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementoffice',
            name='box_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='boxes.BoxOffice', verbose_name='Caja oficina'),
        ),
    ]
