# Generated by Django 2.0.9 on 2019-04-23 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0003_movementbetweenofficerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movementdailysquare',
            name='country',
        ),
        migrations.AddField(
            model_name='movementdailysquare',
            name='movement_cd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movement.MovementDailySquare', verbose_name='Movimiento CD Contrapartida'),
        ),
        migrations.AddField(
            model_name='movementdailysquare',
            name='movement_don_juan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movement.MovementDonJuan', verbose_name='Movimiento Don Juan Contrapartida'),
        ),
        migrations.AddField(
            model_name='movementdailysquare',
            name='movement_don_juan_usd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movement.MovementDonJuanUsd', verbose_name='Movimiento Don Juan Dolares Contrapartida'),
        ),
        migrations.AddField(
            model_name='movementdailysquare',
            name='movement_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movement.MovementOffice', verbose_name='Movimiento Oficina Contrapartida'),
        ),
        migrations.AddField(
            model_name='movementdailysquare',
            name='movement_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movement.MovementPartner', verbose_name='Movimiento Socio Contrapartida'),
        ),
    ]
