# Generated by Django 2.0.9 on 2019-02-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0004_auto_20190130_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementcountry',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP responsable'),
        ),
        migrations.AlterField(
            model_name='movementdailysquare',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP responsable'),
        ),
        migrations.AlterField(
            model_name='movementoffice',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP responsable'),
        ),
        migrations.AlterField(
            model_name='movementpartner',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP responsable'),
        ),
    ]
