# Generated by Django 2.0.9 on 2019-02-04 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0005_auto_20190201_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementcountry',
            name='box_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='boxes.BoxCountry', verbose_name='Caja País'),
        ),
        migrations.AlterField(
            model_name='movementdailysquare',
            name='box_daily_square',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='boxes.BoxDailySquare', verbose_name='Caja Cuadre Diario'),
        ),
        migrations.AlterField(
            model_name='movementpartner',
            name='box_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='boxes.BoxPartner', verbose_name='Caja Socio'),
        ),
    ]
