# Generated by Django 2.0.9 on 2019-04-25 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('movement', '0005_auto_20190424_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementDailySquareRequestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('price', models.IntegerField(help_text='Precio en la modena local', verbose_name='Precio')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_unit_movement_items', to='inventory.Brand', verbose_name='Marca')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_movement_request', to='movement.MovementDailySquare', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Inventario unidad',
                'verbose_name_plural': 'Inventarios unidades',
            },
        ),
    ]
