# Generated by Django 2.0.9 on 2019-04-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0006_movementdailysquarerequestitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movementdailysquarerequestitem',
            options={'verbose_name': 'Movimiento de Aprobación', 'verbose_name_plural': 'Movimientos de aprobación'},
        ),
        migrations.AlterField(
            model_name='movementdailysquarerequestitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='movementdailysquarerequestitem',
            name='price',
            field=models.IntegerField(blank=True, help_text='Precio en la modena local', null=True, verbose_name='Precio'),
        ),
    ]
