# Generated by Django 2.0.9 on 2019-04-26 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0006_movementdailysquarerequestitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movementdailysquarerequestitem',
            options={'verbose_name': 'Movimiento de Aprobación', 'verbose_name_plural': 'Movimientos de aprobación'},
        ),
        migrations.AlterField(
            model_name='movementdailysquare',
            name='movement_cd',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movement.MovementDailySquare', verbose_name='Movimiento CD Contrapartida'),
        ),
        migrations.AlterField(
            model_name='movementdailysquare',
            name='movement_don_juan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movement.MovementDonJuan', verbose_name='Movimiento Don Juan Contrapartida'),
        ),
        migrations.AlterField(
            model_name='movementdailysquare',
            name='movement_don_juan_usd',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movement.MovementDonJuanUsd', verbose_name='Movimiento Don Juan Dolares Contrapartida'),
        ),
        migrations.AlterField(
            model_name='movementdailysquare',
            name='movement_office',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movement.MovementOffice', verbose_name='Movimiento Oficina Contrapartida'),
        ),
        migrations.AlterField(
            model_name='movementdailysquare',
            name='movement_partner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movement.MovementPartner', verbose_name='Movimiento Socio Contrapartida'),
        ),
        migrations.AlterField(
            model_name='movementdailysquarerequestitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='movementdailysquarerequestitem',
            name='price',
            field=models.IntegerField(blank=True, help_text='Precio en la modena local', null=True, verbose_name='Precio'),
        ),
    ]
