# Generated by Django 2.0.9 on 2019-02-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0007_movementdonjuan'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementdailysquare',
            name='denied_detail',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle del rechazo del movimiento'),
        ),
        migrations.AddField(
            model_name='movementdailysquare',
            name='review',
            field=models.BooleanField(default=False, verbose_name='Movimiento Revisado?'),
        ),
        migrations.AddField(
            model_name='movementdailysquare',
            name='status',
            field=models.CharField(blank=True, choices=[('AP', 'Aprovado'), ('DE', 'Rechazado')], max_length=2, null=True, verbose_name='Estado de la revisión'),
        ),
    ]
