# Generated by Django 2.0.9 on 2019-04-06 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0005_auto_20190406_2236'),
        ('concepts', '0002_auto_20190320_2119'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movement', '0007_movementwithdraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementDonJuanUsd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entra'), ('OUT', 'Sale')], max_length=10, verbose_name='Tipo de movimiento')),
                ('value', models.IntegerField(default=0, verbose_name='Valor')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP responsable')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo')),
                ('box_don_juan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='boxes.BoxDonJuanUSD', verbose_name='Caja Don Juan USD')),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='concepts.Concept', verbose_name='Concepto')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Movimiento de Don Juan',
                'verbose_name_plural': 'Movimientos de Don Juan',
            },
        ),
        migrations.RemoveField(
            model_name='movementcountry',
            name='box_country',
        ),
        migrations.RemoveField(
            model_name='movementcountry',
            name='concept',
        ),
        migrations.RemoveField(
            model_name='movementcountry',
            name='responsible',
        ),
        migrations.DeleteModel(
            name='MovementCountry',
        ),
    ]
