# Generated by Django 2.0.9 on 2019-04-08 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0008_auto_20190406_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementdailysquare',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.OfficeCountry', verbose_name='Oficina'),
        ),
    ]
