# Generated by Django 2.0.9 on 2019-02-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0008_auto_20190220_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementdailysquare',
            name='status',
            field=models.CharField(blank=True, choices=[('AP', 'Aprobado'), ('DE', 'Rechazado')], max_length=2, null=True, verbose_name='Estado de la revisión'),
        ),
    ]
