# Generated by Django 2.0.9 on 2019-02-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0009_auto_20190221_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementdailysquare',
            name='status',
            field=models.CharField(blank=True, choices=[('AP', 'Aprobado'), ('DE', 'Rechazado'), ('DI', 'Dispersado')], max_length=2, null=True, verbose_name='Estado de la revisión'),
        ),
    ]
