# Generated by Django 2.0.9 on 2019-05-17 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0007_boxcolombia'),
        ('movement', '0009_movementboxcolombia'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementbetweenofficerequest',
            name='origin_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_between_office_origin', to='boxes.BoxOffice', verbose_name='Caja oficina'),
        ),
    ]
