# Generated by Django 2.0.9 on 2019-08-29 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_partner_buyer_unit_partner'),
        ('movement', '0012_auto_20190719_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementdailysquare',
            name='temp_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Employee', verbose_name='Empleado temporal prestamo'),
        ),
    ]
