# Generated by Django 2.0.9 on 2019-09-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0013_movementdailysquare_temp_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementboxcolombia',
            name='movement_don_juan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movimiento Don Juan PK'),
        ),
        migrations.AddField(
            model_name='movementboxcolombia',
            name='movement_don_juan_usd',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movimiento Don Juan Dólares'),
        ),
        migrations.AddField(
            model_name='movementboxcolombia',
            name='movement_office',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movimiento Oficina PK'),
        ),
        migrations.AddField(
            model_name='movementdonjuan',
            name='movement_box_colombia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movimiento Caja Colombia'),
        ),
        migrations.AddField(
            model_name='movementdonjuan',
            name='movement_don_juan_usd',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movimiento Don Juan Dólares'),
        ),
        migrations.AddField(
            model_name='movementdonjuan',
            name='movement_office',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movimiento Oficina PK'),
        ),
        migrations.AddField(
            model_name='movementdonjuanusd',
            name='movement_box_colombia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movimiento Caja Colombia'),
        ),
        migrations.AddField(
            model_name='movementdonjuanusd',
            name='movement_don_juan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movimiento Don Juan PK'),
        ),
        migrations.AddField(
            model_name='movementdonjuanusd',
            name='movement_office',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movimiento Oficina PK'),
        ),
        migrations.AddField(
            model_name='movementoffice',
            name='movement_don_juan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movimiento Don Juan PK'),
        ),
        migrations.AddField(
            model_name='movementoffice',
            name='movement_don_juan_usd',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movimiento Don Juan Dólares'),
        ),
        migrations.AddField(
            model_name='movementoffice',
            name='movement_office',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movimiento Oficina PK'),
        ),
    ]
