# Generated by Django 2.0.9 on 2019-09-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0016_auto_20190920_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementboxcolombia',
            name='movement_colombia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movimiento Caja Colombia PK'),
        ),
    ]
