# Generated by Django 2.0.9 on 2019-09-20 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0017_movementboxcolombia_movement_colombia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movementboxcolombia',
            old_name='movement_colombia',
            new_name='movement_box_colombia',
        ),
    ]
