# Generated by Django 2.0.9 on 2019-09-26 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0018_auto_20190920_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movementdonjuan',
            options={'ordering': ['-date', '-pk'], 'verbose_name': 'Movimiento de Presidente', 'verbose_name_plural': 'Movimientos de Presidente'},
        ),
        migrations.AlterModelOptions(
            name='movementdonjuanusd',
            options={'ordering': ['-date', '-pk'], 'verbose_name': 'Movimiento de Presidente', 'verbose_name_plural': 'Movimientos de Presidente'},
        ),
        migrations.AlterField(
            model_name='movementbetweenofficerequest',
            name='from_box_type',
            field=models.CharField(choices=[('BDJ', 'Caja de Presidente'), ('BCO', 'Caja Colombia')], default='BDJ', max_length=3, verbose_name='Origen del movimiento'),
        ),
        migrations.AlterField(
            model_name='movementboxcolombia',
            name='movement_don_juan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movimiento Presidente PK'),
        ),
        migrations.AlterField(
            model_name='movementboxcolombia',
            name='movement_don_juan_usd',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movimiento Presidente Dólares PK'),
        ),
        migrations.AlterField(
            model_name='movementdailysquare',
            name='movement_don_juan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movement.MovementDonJuan', verbose_name='Movimiento Presidente Contrapartida'),
        ),
        migrations.AlterField(
            model_name='movementdailysquare',
            name='movement_don_juan_usd',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movement.MovementDonJuanUsd', verbose_name='Movimiento Presidente Dolares Contrapartida'),
        ),
        migrations.AlterField(
            model_name='movementdonjuan',
            name='box_don_juan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='boxes.BoxDonJuan', verbose_name='Caja Presidente Oficina'),
        ),
        migrations.AlterField(
            model_name='movementdonjuan',
            name='movement_don_juan_usd',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movimiento Presidente Dólares PK'),
        ),
        migrations.AlterField(
            model_name='movementdonjuanusd',
            name='box_don_juan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='boxes.BoxDonJuanUSD', verbose_name='Caja Presidente USD'),
        ),
        migrations.AlterField(
            model_name='movementdonjuanusd',
            name='movement_don_juan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movimiento Presidente PK'),
        ),
        migrations.AlterField(
            model_name='movementoffice',
            name='movement_don_juan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movimiento Presidente PK'),
        ),
        migrations.AlterField(
            model_name='movementoffice',
            name='movement_don_juan_usd',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movimiento Presidente Dólares PK'),
        ),
    ]
