# Generated by Django 2.0.9 on 2019-05-29 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingoffice',
            name='month',
            field=models.DateField(default=datetime.date(2019, 5, 29), verbose_name='Mes ranking'),
        ),
    ]
