# Generated by Django 2.0.9 on 2019-06-05 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rankingoffice_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingoffice',
            name='month',
            field=models.DateField(default=datetime.date(2019, 6, 5), verbose_name='Mes ranking'),
        ),
    ]
