# Generated by Django 2.0.9 on 2019-06-11 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20190605_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingoffice',
            name='month',
            field=models.DateField(default=datetime.date(2019, 6, 11), verbose_name='Mes ranking'),
        ),
    ]
