# Generated by Django 2.0.9 on 2019-06-14 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20190611_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingoffice',
            name='month',
            field=models.DateField(default=datetime.date(2019, 6, 14), verbose_name='Mes ranking'),
        ),
    ]
