# Generated by Django 2.0.9 on 2019-06-28 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20190614_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankingoffice',
            name='month',
        ),
        migrations.AddField(
            model_name='rankingoffice',
            name='end_date',
            field=models.DateField(default=datetime.date(2019, 6, 28), verbose_name='Fecha fin ranking'),
        ),
        migrations.AddField(
            model_name='rankingoffice',
            name='start_date',
            field=models.DateField(default=datetime.date(2019, 6, 28), verbose_name='Fecha inicio ranking'),
        ),
    ]
