# Generated by Django 2.0.9 on 2019-07-25 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20190719_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingoffice',
            name='end_date',
            field=models.DateField(default=datetime.date(2019, 7, 25), verbose_name='Fecha fin ranking'),
        ),
        migrations.AlterField(
            model_name='rankingoffice',
            name='start_date',
            field=models.DateField(default=datetime.date(2019, 7, 25), verbose_name='Fecha inicio ranking'),
        ),
    ]
