#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
python /app/manage.py migrate_schemas --executor=parallel --noinput
/usr/local/bin/uwsgi --ini /app/uwsgi.ini --logto /app/uwsgi.log
