# Generated by Django 2.0.9 on 2019-03-12 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre Cadena')),
                ('places', models.IntegerField(default=1, verbose_name='Número de puestos')),
                ('place_value', models.FloatField(default=0, verbose_name='Precio por puesto')),
                ('external_chain', models.BooleanField(default=False, verbose_name='Es una cadena externa?')),
            ],
            options={
                'verbose_name': 'Cadena',
            },
        ),
        migrations.CreateModel(
            name='ChainPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(verbose_name='Fecha de pago del puesto')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_places', to='chains.Chain', verbose_name='Cadena')),
            ],
            options={
                'verbose_name': 'Puesto de la cadena',
                'verbose_name_plural': 'Puestos de la cadena',
            },
        ),
        migrations.CreateModel(
            name='UserPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_porcentaje', models.FloatField(verbose_name='Porcentaje del usuario')),
                ('chain_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_users', to='chains.ChainPlace', verbose_name='Puesto de la cadena')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_chains', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuario por puesto',
                'verbose_name_plural': 'Usuarios por puesto',
            },
        ),
    ]
