# Generated by Django 2.0.9 on 2019-03-12 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
        ('chains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_chaines', to='office.Office', verbose_name='Oficina'),
        ),
    ]
