# Generated by Django 2.0.9 on 2019-03-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0002_chain_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chain',
            name='external_chain',
        ),
        migrations.AddField(
            model_name='chain',
            name='chain_type',
            field=models.CharField(choices=[('IN', 'Interna'), ('EX', 'Externa')], default='IN', max_length=2, verbose_name='Tipo de cadena'),
        ),
    ]
