# Generated by Django 2.0.9 on 2019-03-21 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0002_auto_20190320_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlacePay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_value', models.FloatField(verbose_name='Valor del pago')),
                ('date', models.DateField(verbose_name='Fecha del pago')),
                ('user_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_payments', to='chains.UserPlace', verbose_name='Puesto del usuario')),
            ],
            options={
                'verbose_name': 'Pago del puesto',
                'verbose_name_plural': 'Pagos del puesto',
            },
        ),
    ]
