# Generated by Django 2.0.9 on 2019-03-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0003_auto_20190314_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainplace',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de puesto'),
        ),
    ]
