# Generated by Django 2.0.9 on 2019-04-08 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0003_userplacepay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_chaines', to='office.OfficeCountry', verbose_name='Oficina'),
        ),
    ]
