# Generated by Django 2.0.9 on 2019-03-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0004_chainplace_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chainplace',
            options={'ordering': ['id'], 'verbose_name': 'Puesto de la cadena', 'verbose_name_plural': 'Puestos de la cadena'},
        ),
        migrations.AlterModelOptions(
            name='userplace',
            options={'ordering': ['id'], 'verbose_name': 'Usuario por puesto', 'verbose_name_plural': 'Usuarios por puesto'},
        ),
    ]
