# Generated by Django 2.0.9 on 2019-03-05 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Valor del préstamo (Divisa local)')),
                ('value_cop', models.FloatField(verbose_name='Valor del préstamo (En COP)')),
                ('interest', models.FloatField(verbose_name='Porcentaje de interés')),
                ('time', models.IntegerField(verbose_name='Plazo (en meses)')),
                ('balance', models.FloatField(verbose_name='Saldo a la fecha')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_lender_user', to=settings.AUTH_USER_MODEL, verbose_name='Prestamista')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_provider_loan', to=settings.AUTH_USER_MODEL, verbose_name='Prestador')),
            ],
            options={
                'verbose_name': 'Préstamo',
            },
        ),
    ]
