# Generated by Django 2.0.9 on 2019-04-08 16:14

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import cajas.loans.models.loan


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', enumfields.fields.EnumField(enum=cajas.loans.models.loan.LoanType, max_length=3, verbose_name='Tipo de préstamo')),
                ('value', models.FloatField(verbose_name='Valor del préstamo (Divisa local)')),
                ('value_cop', models.FloatField(verbose_name='Valor del préstamo (En COP)')),
                ('interest', models.FloatField(verbose_name='Porcentaje de interés')),
                ('time', models.IntegerField(blank=True, null=True, verbose_name='Plazo (en meses)')),
                ('balance', models.FloatField(verbose_name='Saldo a la fecha')),
                ('exchange', models.FloatField(default=0, verbose_name='Tasa de cambio')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción del Préstamo (terceros)')),
            ],
            options={
                'verbose_name': 'Préstamo',
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Valor del pago')),
                ('date', models.DateField(verbose_name='Fecha del pago')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_payments', to='loans.Loan', verbose_name='Préstamo')),
            ],
            options={
                'verbose_name': 'Pago del préstamo',
                'verbose_name_plural': 'Pagos del préstamo',
            },
        ),
    ]
