# Generated by Django 2.0.9 on 2019-03-05 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Valor del pago')),
                ('date', models.DateField(verbose_name='Fecha del pago')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.Loan', verbose_name='Préstamo')),
            ],
            options={
                'verbose_name': 'Pago del préstamo',
                'verbose_name_plural': 'Pagos del préstamo',
            },
        ),
    ]
