# Generated by Django 2.0.9 on 2019-03-05 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0013_auto_20190228_1604'),
        ('loans', '0002_loanpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.Office', verbose_name='Oficina'),
        ),
    ]
