# Generated by Django 2.0.9 on 2019-05-14 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20190408_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_type', models.CharField(choices=[('LO', 'Prestamo'), ('IN', 'Interes'), ('AB', 'Abono')], max_length=2, null=True, verbose_name='Tipo de movimiento')),
                ('value', models.FloatField(verbose_name='Valor del pago')),
                ('date', models.DateField(verbose_name='Fecha del pago')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_payments', to='loans.Loan', verbose_name='Préstamo')),
            ],
            options={
                'verbose_name': 'Historial de préstamo',
                'verbose_name_plural': 'Historial de préstamos',
            },
        ),
        migrations.RemoveField(
            model_name='loanpayment',
            name='loan',
        ),
        migrations.DeleteModel(
            name='LoanPayment',
        ),
    ]
