# Generated by Django 2.0.9 on 2019-03-11 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20190311_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_payments', to='loans.Loan', verbose_name='Préstamo'),
        ),
    ]
