# Generated by Django 2.0.9 on 2019-04-06 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20190320_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.OfficeCountry', verbose_name='Oficina'),
        ),
    ]
