# Generated by Django 2.0.9 on 2019-05-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_auto_20190514_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanhistory',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Entra'), ('OUT', 'Sale')], max_length=10, null=True, verbose_name='Tipo de movimiento'),
        ),
    ]
