# Generated by Django 2.0.9 on 2019-03-05 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import loans.models.loan


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=enumfields.fields.EnumField(default='DIR', enum=loans.models.loan.LoanType, max_length=3, verbose_name='Tipo de préstamo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_lender_user', to=settings.AUTH_USER_MODEL, verbose_name='Deudor'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_provider_loan', to=settings.AUTH_USER_MODEL, verbose_name='Fondeador'),
        ),
    ]
