# Generated by Django 2.0.9 on 2019-05-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loanhistory_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanhistory',
            name='history_type',
            field=models.CharField(choices=[('LO', 'Prestamo'), ('IN', 'Interes'), ('AB', 'Abono')], max_length=2, null=True, verbose_name='Tipo de historial'),
        ),
        migrations.AlterField(
            model_name='loanhistory',
            name='value',
            field=models.FloatField(verbose_name='Valor'),
        ),
    ]
