# Generated by Django 2.0.9 on 2019-05-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_auto_20190515_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='balance_cop',
            field=models.FloatField(default=0, verbose_name='Saldo a la fecha'),
        ),
        migrations.AddField(
            model_name='loanhistory',
            name='value_cop',
            field=models.FloatField(default=0, verbose_name='Valor en COP'),
        ),
    ]
