# Generated by Django 2.0.9 on 2019-03-07 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loan_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_provider_loan', to=settings.AUTH_USER_MODEL, verbose_name='Fondeador'),
        ),
    ]
