# Generated by Django 2.0.9 on 2019-03-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_auto_20190307_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Plazo (en meses)'),
        ),
    ]
