# Generated by Django 2.0.9 on 2019-07-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_auto_20190527_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanhistory',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Saldo a la Fecha'),
        ),
    ]
