# Generated by Django 2.0.9 on 2019-03-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_auto_20190308_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del Préstamo (terceros)'),
        ),
    ]
