# Generated by Django 2.0.9 on 2019-07-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_loanhistory_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanhistory',
            name='balance_cop',
            field=models.FloatField(default=0, verbose_name='Saldo a la Fecha (COP)'),
        ),
    ]
