# Generated by Django 2.0.9 on 2019-08-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_loanhistory_balance_cop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanhistory',
            name='history_type',
            field=models.CharField(choices=[('LO', 'Préstamo'), ('IN', 'Interés'), ('AB', 'Abono')], max_length=2, null=True, verbose_name='Tipo de historial'),
        ),
    ]
