# Generated by Django 2.0.9 on 2019-09-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_auto_20190801_2335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanhistory',
            options={'ordering': ['date', 'pk'], 'verbose_name': 'Historial de préstamo', 'verbose_name_plural': 'Historial de préstamos'},
        ),
    ]
