# Generated by Django 2.0.9 on 2018-12-19 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_collector_units', to=settings.AUTH_USER_MODEL, verbose_name='Cobrador')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_units', to=settings.AUTH_USER_MODEL, verbose_name='Socio')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_supervisor_units', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='UnitItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('price', models.IntegerField(help_text='Precio en la modena local', verbose_name='Precio')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Item Eliminado?')),
                ('observations', models.TextField(blank=True, help_text='Por que se elimino el item?', null=True, verbose_name='Observaciones')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_unit_items', to='inventory.Brand', verbose_name='Marca')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_items', to='units.Unit', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Inventario unidad',
                'verbose_name_plural': 'Inventarios unidades',
            },
        ),
    ]
