# Generated by Django 2.0.9 on 2019-04-27 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_notifications'),
        ('units', '0002_auto_20190408_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='unititems',
            name='is_replacement',
            field=models.BooleanField(default=False, verbose_name='Item de repuesto?'),
        ),
        migrations.AddField(
            model_name='unititems',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.OfficeCountry', verbose_name='Oficina por país'),
        ),
        migrations.AlterField(
            model_name='unititems',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_items', to='units.Unit', verbose_name='Unidad'),
        ),
    ]
