# Generated by Django 2.0.9 on 2019-01-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20190116_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Unidad Activa'),
        ),
    ]
