# Generated by Django 2.0.9 on 2019-03-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20190311_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='observations',
            field=models.TextField(blank=True, help_text='Por que se elimino el item?', null=True, verbose_name='Observaciones'),
        ),
    ]
