# Generated by Django 2.0.9 on 2019-09-25 17:05

from django.db import migrations, models
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_auto_20190917_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='domain_url',
            field=models.CharField(max_length=128, unique=True, verbose_name='Dominio'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='schema_name',
            field=models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name], verbose_name='Esquema'),
        ),
    ]
