# Generated by Django 2.0.9 on 2019-01-18 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0013_auto_20190116_1519'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0007_officeitems_brand'),
        ('general_config', '0002_country_abbr'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo de la caja')),
                ('is_active', models.BooleanField(default=True, verbose_name='Caja Activa?')),
                ('country', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general_config.Country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Caja de país',
                'verbose_name_plural': 'Cajas de paises',
            },
        ),
        migrations.CreateModel(
            name='BoxDailySquare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo de la caja')),
                ('is_active', models.BooleanField(default=True, verbose_name='Caja Activa?')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Caja de socio',
                'verbose_name_plural': 'Cajas de socios',
            },
        ),
        migrations.CreateModel(
            name='BoxOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo de la caja')),
                ('is_active', models.BooleanField(default=True, verbose_name='Caja Activa?')),
                ('office', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.Office', verbose_name='Oficina')),
            ],
            options={
                'verbose_name': 'Caja de oficinas',
                'verbose_name_plural': 'Cajas de Oficina',
            },
        ),
        migrations.CreateModel(
            name='BoxPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo de la caja')),
                ('is_active', models.BooleanField(default=True, verbose_name='Caja Activa?')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Partner', verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Caja de socio',
                'verbose_name_plural': 'Cajas de socios',
            },
        ),
    ]
