# Generated by Django 2.0.9 on 2019-03-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo de la caja')),
                ('is_active', models.BooleanField(default=True, verbose_name='Caja Activa?')),
                ('last_movement_id', models.IntegerField(default=0, verbose_name='id último movimiento')),
            ],
            options={
                'verbose_name': 'Caja de País',
                'verbose_name_plural': 'Cajas de Paises',
            },
        ),
        migrations.CreateModel(
            name='BoxDailySquare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo de la caja')),
                ('is_active', models.BooleanField(default=True, verbose_name='Caja Activa?')),
                ('last_movement_id', models.IntegerField(default=0, verbose_name='id último movimiento')),
            ],
            options={
                'verbose_name': 'Caja de Cuadre Diario',
                'verbose_name_plural': 'Cajas de Cuadre Diario',
            },
        ),
        migrations.CreateModel(
            name='BoxDonJuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo de la caja')),
                ('is_active', models.BooleanField(default=True, verbose_name='Caja Activa?')),
                ('last_movement_id', models.IntegerField(default=0, verbose_name='id último movimiento')),
            ],
            options={
                'verbose_name': 'Caja de Don Juan',
                'verbose_name_plural': 'Cajas de Don Juan',
            },
        ),
        migrations.CreateModel(
            name='BoxOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo de la caja')),
                ('is_active', models.BooleanField(default=True, verbose_name='Caja Activa?')),
                ('last_movement_id', models.IntegerField(default=0, verbose_name='id último movimiento')),
            ],
            options={
                'verbose_name': 'Caja de oficinas',
                'verbose_name_plural': 'Cajas de Oficina',
            },
        ),
        migrations.CreateModel(
            name='BoxPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo de la caja')),
                ('is_active', models.BooleanField(default=True, verbose_name='Caja Activa?')),
                ('last_movement_id', models.IntegerField(default=0, verbose_name='id último movimiento')),
            ],
            options={
                'verbose_name': 'Caja de socio',
                'verbose_name_plural': 'Cajas de socios',
            },
        ),
    ]
