# Generated by Django 2.0.9 on 2019-04-08 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0001_initial'),
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxprovisioning',
            name='office',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box_provisioning', to='office.OfficeCountry', verbose_name='Oficina'),
        ),
    ]
