# Generated by Django 2.0.9 on 2019-03-11 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boxes', '0001_initial'),
        ('users', '0001_initial'),
        ('office', '0001_initial'),
        ('general_config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boxpartner',
            name='partner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box', to='users.Partner', verbose_name='Socio'),
        ),
        migrations.AddField(
            model_name='boxoffice',
            name='office',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box', to='office.Office', verbose_name='Oficina'),
        ),
        migrations.AddField(
            model_name='boxdonjuan',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.Office', verbose_name='Oficina'),
        ),
        migrations.AddField(
            model_name='boxdonjuan',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Partner', verbose_name='Don Juan'),
        ),
        migrations.AddField(
            model_name='boxdailysquare',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_daily_square_boxes', to='office.Office', verbose_name='Oficina'),
        ),
        migrations.AddField(
            model_name='boxdailysquare',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='boxcountry',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box', to='general_config.Country', verbose_name='País'),
        ),
        migrations.AddField(
            model_name='boxcountry',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general_config.Currency', verbose_name='Divisa de la caja'),
        ),
        migrations.AlterUniqueTogether(
            name='boxcountry',
            unique_together={('country', 'currency')},
        ),
    ]
