# Generated by Django 2.0.9 on 2019-03-26 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
        ('boxes', '0002_auto_20190320_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxProvisioning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo de la caja')),
                ('is_active', models.BooleanField(default=True, verbose_name='Caja Activa?')),
                ('last_movement_id', models.IntegerField(default=0, verbose_name='id último movimiento')),
                ('office', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box_provisioning', to='office.Office', verbose_name='Oficina')),
            ],
            options={
                'verbose_name': 'Caja de aprovisionamiento',
                'verbose_name_plural': 'Cajas de aprovisionamientos',
            },
        ),
    ]
