# Generated by Django 2.0.9 on 2019-01-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_config', '0003_auto_20190125_1556'),
        ('boxes', '0003_boxcountry_currency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boxcountry',
            unique_together={('country', 'currency')},
        ),
    ]
