# Generated by Django 2.0.9 on 2019-03-28 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0003_boxprovisioning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxdailysquare',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_daily_box', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
