# Generated by Django 2.0.9 on 2019-04-09 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0003_auto_20190408_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxdonjuanusd',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_usd_box', to='office.OfficeCountry', verbose_name='Oficina por país'),
        ),
    ]
