# Generated by Django 2.0.9 on 2019-04-06 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0004_auto_20190328_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxDonJuanUSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo de la caja')),
                ('is_active', models.BooleanField(default=True, verbose_name='Caja Activa?')),
                ('last_movement_id', models.IntegerField(default=0, verbose_name='id último movimiento')),
            ],
            options={
                'verbose_name': 'Caja de Don Juan',
                'verbose_name_plural': 'Cajas de Don Juan',
            },
        ),
        migrations.AlterUniqueTogether(
            name='boxcountry',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='boxcountry',
            name='country',
        ),
        migrations.RemoveField(
            model_name='boxcountry',
            name='currency',
        ),
        migrations.AlterField(
            model_name='boxdailysquare',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_daily_square_boxes', to='office.OfficeCountry', verbose_name='Oficina'),
        ),
        migrations.AlterField(
            model_name='boxdonjuan',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.OfficeCountry', verbose_name='Oficina por país'),
        ),
        migrations.AlterField(
            model_name='boxoffice',
            name='office',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box', to='office.OfficeCountry', verbose_name='Oficina del País'),
        ),
        migrations.AlterField(
            model_name='boxprovisioning',
            name='office',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box_provisioning', to='office.OfficeCountry', verbose_name='Oficina'),
        ),
    ]
