# Generated by Django 2.0.9 on 2019-01-25 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0004_auto_20190125_1624'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boxcountry',
            unique_together=set(),
        ),
    ]
