# Generated by Django 2.0.9 on 2019-04-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0004_auto_20190409_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxdailysquare',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Caja cerrada?'),
        ),
    ]
