# Generated by Django 2.0.9 on 2019-04-06 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0008_auto_20190406_2236'),
        ('boxes', '0005_auto_20190406_2236'),
        ('office', '0003_auto_20190405_2140'),
        ('users', '0005_auto_20190405_2140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoxCountry',
        ),
        migrations.AddField(
            model_name='boxdonjuanusd',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.OfficeCountry', verbose_name='Oficina por país'),
        ),
        migrations.AddField(
            model_name='boxdonjuanusd',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Partner', verbose_name='Don Juan'),
        ),
    ]
