# Generated by Django 2.0.9 on 2019-04-15 16:17

import cajas.boxes.models.box_partner
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0005_boxdailysquare_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxpartner',
            name='box_status',
            field=enumfields.fields.EnumField(default='ABIERTA', enum=cajas.boxes.models.box_partner.BoxStatus, max_length=10, verbose_name='Estado de la caja'),
        ),
    ]
