# Generated by Django 2.0.9 on 2019-01-25 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_config', '0003_auto_20190125_1556'),
        ('boxes', '0005_auto_20190125_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxcountry',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general_config.Country', verbose_name='País'),
        ),
        migrations.AlterUniqueTogether(
            name='boxcountry',
            unique_together={('country', 'currency')},
        ),
    ]
