# Generated by Django 2.0.9 on 2019-04-08 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0006_auto_20190406_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boxdonjuanusd',
            options={'verbose_name': 'Caja de Don Juan Dolares', 'verbose_name_plural': 'Cajas de Don Juan Dolares'},
        ),
    ]
