# Generated by Django 2.0.9 on 2019-04-29 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_auto_20190426_1629'),
        ('boxes', '0006_boxpartner_box_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxColombia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Oficina')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo de la caja')),
                ('is_active', models.BooleanField(default=True, verbose_name='Caja Activa?')),
                ('last_movement_id', models.IntegerField(default=0, verbose_name='id último movimiento')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box_colombia', to='office.OfficeCountry', verbose_name='Oficina del País')),
            ],
            options={
                'verbose_name': 'Caja Colombia',
                'verbose_name_plural': 'Cajas Colombia',
            },
        ),
    ]
