# Generated by Django 2.0.9 on 2019-02-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0008_auto_20190128_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxcountry',
            name='last_movement_id',
            field=models.IntegerField(default=0, verbose_name='id último movimiento'),
        ),
        migrations.AddField(
            model_name='boxdailysquare',
            name='last_movement_id',
            field=models.IntegerField(default=0, verbose_name='id último movimiento'),
        ),
        migrations.AddField(
            model_name='boxoffice',
            name='last_movement_id',
            field=models.IntegerField(default=0, verbose_name='id último movimiento'),
        ),
        migrations.AddField(
            model_name='boxpartner',
            name='last_movement_id',
            field=models.IntegerField(default=0, verbose_name='id último movimiento'),
        ),
    ]
