# Generated by Django 2.0.9 on 2019-02-13 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0010_boxdonjuan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxpartner',
            name='partner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box', to='users.Partner', verbose_name='Socio'),
        ),
    ]
