# Generated by Django 2.0.9 on 2019-02-15 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0012_auto_20190204_2210'),
        ('boxes', '0011_auto_20190213_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxdailysquare',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_daily_square_boxes', to='office.Office', verbose_name='Oficina'),
        ),
    ]
