# Generated by Django 2.0.9 on 2019-02-21 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0012_boxdailysquare_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxcountry',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box', to='general_config.Country', verbose_name='País'),
        ),
    ]
