# Generated by Django 2.0.9 on 2019-04-03 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20190402_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('element', models.TextField(verbose_name='Elemento que se negocia')),
                ('total_value', models.IntegerField(verbose_name='Valor Total')),
                ('conditions', models.TextField(verbose_name='Condiciones de la negociación')),
                ('initial_value', models.IntegerField(verbose_name='Cuota inicial')),
                ('investment_type', models.CharField(choices=[('PE', 'Personal'), ('BS', 'Negocio')], max_length=2, verbose_name='Tipo de inversión')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_investments', to='users.Partner', verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Inversión Negocios',
                'verbose_name_plural': 'Inversiones Negocios',
            },
        ),
    ]
