# Generated by Django 2.0.9 on 2019-04-08 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('element', models.TextField(verbose_name='Elemento que se negocia')),
                ('total_value', models.IntegerField(verbose_name='Valor Total')),
                ('balance', models.IntegerField(default=0, verbose_name='Saldo a la fecha')),
                ('conditions', models.TextField(verbose_name='Condiciones de la negociación')),
                ('initial_value', models.IntegerField(verbose_name='Cuota inicial')),
                ('monthly_pay', models.IntegerField(default=0, verbose_name='Valor pago mensual')),
                ('time', models.IntegerField(blank=True, null=True, verbose_name='Plazo (en meses)')),
                ('investment_type', models.CharField(choices=[('PE', 'Personal'), ('BS', 'Negocio')], max_length=2, verbose_name='Tipo de inversión')),
            ],
            options={
                'verbose_name': 'Inversión Negocios',
                'verbose_name_plural': 'Inversiones Negocios',
            },
        ),
        migrations.CreateModel(
            name='InvestmentPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Valor del pago')),
                ('detail', models.TextField(default='', verbose_name='Detalle del pago')),
                ('date', models.DateField(verbose_name='Fecha del pago')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_pays', to='investments.Investment', verbose_name='Inversión')),
            ],
            options={
                'verbose_name': 'Pago de Inversión',
                'verbose_name_plural': 'Pagos de Inversión',
            },
        ),
    ]
