# Generated by Django 2.0.9 on 2019-04-03 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Valor del pago')),
                ('date', models.DateField(verbose_name='Fecha del pago')),
            ],
            options={
                'verbose_name': 'Pago de Inversión',
                'verbose_name_plural': 'Pagos de Inversión',
            },
        ),
        migrations.AddField(
            model_name='investment',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Saldo a la fecha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentpay',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_pays', to='investments.Investment', verbose_name='Inversión'),
        ),
    ]
