# Generated by Django 2.0.9 on 2019-04-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_auto_20190403_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Saldo a la fecha'),
        ),
    ]
