# Generated by Django 2.0.9 on 2019-09-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_investment_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentpay',
            name='value_cop',
            field=models.IntegerField(default=0, verbose_name='Valor del pago COP'),
        ),
    ]
