# Generated by Django 2.0.9 on 2019-04-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_auto_20190404_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='monthly_pay',
            field=models.IntegerField(default=0, verbose_name='Valor pago mensual'),
        ),
        migrations.AddField(
            model_name='investment',
            name='time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Plazo (en meses)'),
        ),
    ]
