# Generated by Django 2.0.9 on 2019-09-19 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_investmentpay_value_cop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentpay',
            options={'ordering': ['date', 'pk'], 'verbose_name': 'Pago de Inversión', 'verbose_name_plural': 'Pagos de Inversión'},
        ),
    ]
