# Generated by Django 2.0.9 on 2019-04-08 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='Número de la oficina')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefono')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion')),
                ('consecutive', models.IntegerField(default=1, verbose_name='Consecutivo Socios')),
                ('image', models.ImageField(blank=True, null=True, upload_to='contries/', verbose_name='Imágen')),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='OfficeCommitments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('periodicidad', models.CharField(blank=True, choices=[('MO', 'Mensual'), ('SE', 'Semanal')], max_length=2, null=True, verbose_name='Periodicidad')),
                ('value', models.IntegerField(verbose_name='Valor')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Compromiso Oficina',
                'verbose_name_plural': 'Compromisos Oficina',
            },
        ),
        migrations.CreateModel(
            name='OfficeCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Oficina por país',
                'verbose_name_plural': 'Oficinas por país',
            },
        ),
        migrations.CreateModel(
            name='OfficeItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('price', models.IntegerField(help_text='Precio en la modena local', verbose_name='Precio')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Item Eliminado?')),
                ('observations', models.TextField(blank=True, help_text='Por que se elimino el item?', null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Inventario oficina',
                'verbose_name_plural': 'Inventarios oficinas',
            },
        ),
        migrations.CreateModel(
            name='SupervisorCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now=True, verbose_name='Fecha de calendario de supervisor')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_supervisor_calendar', to='office.OfficeCountry', verbose_name='Oficina')),
            ],
            options={
                'verbose_name': 'Calendario de supervisor',
                'verbose_name_plural': 'Calendarios de supervisores',
            },
        ),
    ]
