# Generated by Django 2.0.9 on 2019-03-20 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_config', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='Número de la oficina')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefono')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='slug')),
                ('consecutive', models.IntegerField(default=1, verbose_name='Consecutivo Socios')),
                ('image', models.ImageField(blank=True, null=True, upload_to='contries/', verbose_name='Imágen')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_offices', to='general_config.Country', verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='OfficeCommitments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('periodicidad', models.CharField(blank=True, choices=[('MO', 'Mensual'), ('SE', 'Semanal')], max_length=2, null=True, verbose_name='Periodicidad')),
                ('value', models.IntegerField(verbose_name='Valor')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_commitments', to='office.Office', verbose_name='Oficina')),
            ],
            options={
                'verbose_name': 'Compromiso Oficina',
                'verbose_name_plural': 'Compromisos Oficina',
            },
        ),
        migrations.CreateModel(
            name='OfficeItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('price', models.IntegerField(help_text='Precio en la modena local', verbose_name='Precio')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Item Eliminado?')),
                ('observations', models.TextField(blank=True, help_text='Por que se elimino el item?', null=True, verbose_name='Observaciones')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_office_items', to='inventory.Brand', verbose_name='Marca')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_items', to='office.Office', verbose_name='Oficina')),
            ],
            options={
                'verbose_name': 'Inventario oficina',
                'verbose_name_plural': 'Inventarios oficinas',
            },
        ),
    ]
