# Generated by Django 2.0.9 on 2018-12-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='office',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefono'),
        ),
    ]
