# Generated by Django 2.0.9 on 2019-03-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['number'], 'verbose_name': 'Oficina', 'verbose_name_plural': 'Oficinas'},
        ),
    ]
