# Generated by Django 2.0.9 on 2019-04-05 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_config', '0001_initial'),
        ('office', '0002_supervisorcalendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_office_country', to='general_config.Country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Oficina por país',
                'verbose_name_plural': 'Oficinas por país',
            },
        ),
        migrations.RemoveField(
            model_name='office',
            name='country',
        ),
        migrations.AddField(
            model_name='officecountry',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_office_country', to='office.Office', verbose_name='Oficina'),
        ),
    ]
