# Generated by Django 2.0.9 on 2018-12-19 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_auto_20181219_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Item Eliminado?')),
                ('observations', models.TextField(help_text='Por que se elimino el item?', verbose_name='Observaciones')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_items', to='office.Office', verbose_name='Oficina')),
            ],
            options={
                'verbose_name': 'Inventario oficina',
                'verbose_name_plural': 'Inventarios oficinas',
            },
        ),
    ]
