# Generated by Django 2.0.9 on 2019-04-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_auto_20190405_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='slug',
        ),
        migrations.AddField(
            model_name='officecountry',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='slug'),
        ),
    ]
