# Generated by Django 2.0.9 on 2019-04-09 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0002_auto_20190408_1614'),
        ('office', '0004_remove_office_consecutive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(default='', verbose_name='Detalle del pago')),
                ('value', models.FloatField(verbose_name='Valor del pago')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concepts.Concept', verbose_name='Concepto')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_supervisor_calendar', to='office.Office', verbose_name='Oficina')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notificationes',
            },
        ),
    ]
