# Generated by Django 2.0.9 on 2018-12-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_auto_20181219_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeitems',
            name='observations',
            field=models.TextField(blank=True, help_text='Por que se elimino el item?', null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='officeitems',
            name='price',
            field=models.IntegerField(help_text='Precio en la modena local', verbose_name='Precio'),
        ),
    ]
