# Generated by Django 2.0.9 on 2019-04-08 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_auto_20190407_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorcalendar',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_supervisor_calendar', to='office.OfficeCountry', verbose_name='Oficina'),
        ),
    ]
