# Generated by Django 2.0.9 on 2019-04-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='image',
        ),
        migrations.AddField(
            model_name='officecountry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='office_images/', verbose_name='Imágen'),
        ),
    ]
