# Generated by Django 2.0.9 on 2018-12-19 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_auto_20181219_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeCommitments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('periodicidad', models.CharField(blank=True, choices=[('MO', 'Mensual'), ('SE', 'Semanal')], max_length=2, null=True, verbose_name='Periodicidad')),
                ('value', models.IntegerField(verbose_name='Valor')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_commitments', to='office.Office', verbose_name='Oficina')),
            ],
            options={
                'verbose_name': 'Compromiso Oficina',
                'verbose_name_plural': 'Compromisos Oficina',
            },
        ),
    ]
