# Generated by Django 2.0.9 on 2018-12-19 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('office', '0006_officecommitments'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeitems',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_office_items', to='inventory.Brand', verbose_name='Marca'),
        ),
    ]
