# Generated by Django 2.0.9 on 2019-01-25 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_officeitems_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='admin_junior',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_junior_office', to='users.Employee', verbose_name='Adminsitrador Junior'),
        ),
        migrations.AlterField(
            model_name='office',
            name='admin_senior',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_senior_office', to='users.Employee', verbose_name='Adminsitrador Senior'),
        ),
        migrations.AlterField(
            model_name='office',
            name='secretary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_secretary_office', to='users.Employee', verbose_name='Secretaria'),
        ),
    ]
