# Generated by Django 2.0.9 on 2019-05-02 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_supervisorcalendar_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeitems',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_items', to='office.OfficeCountry', verbose_name='Oficina'),
        ),
    ]
