# Generated by Django 2.0.9 on 2019-02-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_auto_20190125_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='slug'),
        ),
    ]
