# Generated by Django 2.0.9 on 2019-02-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_office_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='name',
        ),
        migrations.AddField(
            model_name='office',
            name='number',
            field=models.IntegerField(default=1, max_length=255, verbose_name='Número de la oficina'),
        ),
    ]
