# Generated by Django 2.0.9 on 2019-02-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0011_auto_20190204_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='consecutive',
            field=models.IntegerField(default=1, verbose_name='Consecutivo Socios'),
        ),
    ]
