# Generated by Django 2.0.9 on 2019-02-28 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0012_auto_20190204_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contries/', verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='office',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_offices', to='general_config.Country', verbose_name='Pais'),
        ),
    ]
