# Generated by Django 2.0.9 on 2019-03-06 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0013_auto_20190228_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='admin_junior',
        ),
        migrations.RemoveField(
            model_name='office',
            name='admin_senior',
        ),
        migrations.RemoveField(
            model_name='office',
            name='secretary',
        ),
    ]
